import { LXGW_WenKai_Mono_TC } from "next/font/google";
import "./globals.css";

const wenkaiMono = LXGW_WenKai_Mono_TC({
  variable: "--font-wenkai-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${wenkaiMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
